### ISSUE TITLE
GitHub Action: Automatic installation with CI is faild. 

### ISSUE THREAD

**Issue by TomoakiNagahara** [TomoakiNagahara/op-app-skeleton-2022#13]
❌ yum install -y php74-apcu
⭕ apt install -y php74-apcu

**Comment by TomoakiNagahara** [comment]
`apt install php74-apcu` is failed. Because it's not root.
Maybe, requires it to be installed beforehand.

**Comment by TomoakiNagahara** [comment]
Could installed.

```
      - name: Setup PHP
        uses: shivammathur/setup-php@v2 # https://github.com/marketplace/actions/setup-php-action
      # uses: nanasess/setup-php@v3     # https://github.com/marketplace/actions/setup-php-environment
        with:
          php-version: ${{ matrix.php }}
          extensions: apcu
```
